# For cross-compiling CEN64 with mingw64-x86_64.

set(CMAKE_SYSTEM_NAME Windows)

SET(PREFIX x86_64-w64-mingw32)
SET(CMAKE_C_COMPILER   ${PREFIX}-gcc)
SET(CMAKE_CXX_COMPILER ${PREFIX}-g++)
SET(CMAKE_AR           ${PREFIX}-gcc-ar)
SET(CMAKE_NM           ${PREFIX}-gcc-nm)
SET(CMAKE_RC_COMPILER  ${PREFIX}-windres)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

